-- InstallerLab Analytics account foundation
-- Safe, additive schema for the website account layer.
-- Run in the InstallerLab Supabase SQL editor before enabling the account gate.
-- Desktop InstallerLab remains unrestricted; these rules apply only to the web Analytics service.

begin;

create table if not exists public.account_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.account_entitlements (
  user_id uuid primary key references auth.users(id) on delete cascade,
  tier text not null default 'free' check (tier in ('free','supporter','pro')),
  max_apps integer not null default 1 check (max_apps >= 1 and max_apps <= 1000),
  supporter boolean not null default false,
  pro boolean not null default false,
  verified_at timestamptz,
  note text,
  updated_at timestamptz not null default now()
);

create table if not exists public.account_analytics_projects (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  track_id text not null unique,
  app_name text,
  active boolean not null default true,
  drive_file_id text,
  drive_file_name text,
  last_archive_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint account_analytics_projects_track_format check (track_id ~ '^IL-TRK-[0-9A-F]{24}$')
);
create index if not exists account_analytics_projects_user_idx on public.account_analytics_projects(user_id, active);

-- OAuth refresh/access tokens must NOT be stored here. Keep secrets in a server-side
-- secret store / Edge Function environment. This table stores only public connection state.
create table if not exists public.account_drive_connections (
  user_id uuid primary key references auth.users(id) on delete cascade,
  connected boolean not null default false,
  provider text not null default 'google',
  provider_email text,
  root_folder_id text,
  connected_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.analytics_archive_batches (
  id bigint generated by default as identity primary key,
  project_id uuid not null references public.account_analytics_projects(id) on delete cascade,
  archive_date date not null,
  row_count integer not null default 0,
  checksum text,
  drive_file_id text,
  status text not null default 'pending' check (status in ('pending','writing','verified','failed')),
  archived_at timestamptz,
  verified_at timestamptz,
  error_message text,
  created_at timestamptz not null default now(),
  unique(project_id, archive_date)
);

alter table public.account_profiles enable row level security;
alter table public.account_entitlements enable row level security;
alter table public.account_analytics_projects enable row level security;
alter table public.account_drive_connections enable row level security;
alter table public.analytics_archive_batches enable row level security;

drop policy if exists "profile_read_own" on public.account_profiles;
create policy "profile_read_own" on public.account_profiles for select to authenticated using (user_id = auth.uid());
drop policy if exists "profile_update_own" on public.account_profiles;
create policy "profile_update_own" on public.account_profiles for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "entitlement_read_own" on public.account_entitlements;
create policy "entitlement_read_own" on public.account_entitlements for select to authenticated using (user_id = auth.uid());

drop policy if exists "analytics_project_read_own" on public.account_analytics_projects;
create policy "analytics_project_read_own" on public.account_analytics_projects for select to authenticated using (user_id = auth.uid());

drop policy if exists "drive_read_own" on public.account_drive_connections;
create policy "drive_read_own" on public.account_drive_connections for select to authenticated using (user_id = auth.uid());

drop policy if exists "archive_read_own" on public.analytics_archive_batches;
create policy "archive_read_own" on public.analytics_archive_batches for select to authenticated using (
  exists (
    select 1 from public.account_analytics_projects p
    where p.id = analytics_archive_batches.project_id and p.user_id = auth.uid()
  )
);

create or replace function public.handle_new_installerlab_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.account_profiles(user_id,email,display_name)
  values(new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name',new.raw_user_meta_data->>'name'))
  on conflict (user_id) do nothing;

  insert into public.account_entitlements(user_id,tier,max_apps,supporter,pro)
  values(new.id,'free',1,false,false)
  on conflict (user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_installerlab_user_created on auth.users;
create trigger on_installerlab_user_created
after insert on auth.users
for each row execute function public.handle_new_installerlab_user();

-- Backfill users that existed before this migration.
insert into public.account_profiles(user_id,email,display_name)
select id,email,coalesce(raw_user_meta_data->>'full_name',raw_user_meta_data->>'name') from auth.users
on conflict (user_id) do nothing;
insert into public.account_entitlements(user_id,tier,max_apps,supporter,pro)
select id,'free',1,false,false from auth.users
on conflict (user_id) do nothing;

create or replace function public.account_summary()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  result jsonb;
begin
  if uid is null then raise exception 'Authentication required'; end if;

  select jsonb_build_object(
    'profile', coalesce((select to_jsonb(p) - 'user_id' from public.account_profiles p where p.user_id=uid),'{}'::jsonb),
    'entitlement', coalesce((select to_jsonb(e) - 'user_id' from public.account_entitlements e where e.user_id=uid),jsonb_build_object('tier','free','max_apps',1,'supporter',false,'pro',false)),
    'projects', coalesce((select jsonb_agg(to_jsonb(x) - 'user_id' order by x.created_at) from public.account_analytics_projects x where x.user_id=uid and x.active),'[]'::jsonb),
    'drive', coalesce((select to_jsonb(d) - 'user_id' from public.account_drive_connections d where d.user_id=uid),jsonb_build_object('connected',false,'provider','google'))
  ) into result;
  return result;
end;
$$;

create or replace function public.register_analytics_project(p_track_id text, p_app_name text default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  clean_track text := upper(trim(coalesce(p_track_id,'')));
  allowed integer := 1;
  used integer := 0;
  existing_owner uuid;
  project_row public.account_analytics_projects;
begin
  if uid is null then raise exception 'Authentication required'; end if;
  if clean_track !~ '^IL-TRK-[0-9A-F]{24}$' then raise exception 'Invalid TrackID format'; end if;

  select user_id into existing_owner from public.account_analytics_projects where track_id=clean_track;
  if existing_owner is not null and existing_owner <> uid then
    raise exception 'This TrackID is already registered to another account';
  end if;

  select coalesce(max_apps,1) into allowed from public.account_entitlements where user_id=uid;
  allowed := coalesce(allowed,1);
  select count(*) into used from public.account_analytics_projects where user_id=uid and active and track_id<>clean_track;
  if used >= allowed then
    raise exception 'Analytics application limit reached for this account';
  end if;

  insert into public.account_analytics_projects(user_id,track_id,app_name,active)
  values(uid,clean_track,nullif(trim(p_app_name),''),true)
  on conflict (track_id) do update set
    app_name=coalesce(excluded.app_name,public.account_analytics_projects.app_name),
    active=true,
    updated_at=now()
  where public.account_analytics_projects.user_id=uid
  returning * into project_row;

  return to_jsonb(project_row) - 'user_id';
end;
$$;

create or replace function public.remove_analytics_project(p_track_id text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare uid uuid := auth.uid();
begin
  if uid is null then raise exception 'Authentication required'; end if;
  update public.account_analytics_projects
     set active=false,updated_at=now()
   where user_id=uid and track_id=upper(trim(coalesce(p_track_id,'')));
end;
$$;

grant execute on function public.account_summary() to authenticated;
grant execute on function public.register_analytics_project(text,text) to authenticated;
grant execute on function public.remove_analytics_project(text) to authenticated;

-- Initial policy. Change only in the entitlement table; no desktop update required.
-- free      = 1 Analytics application
-- supporter = suggested 5 applications
-- pro       = suggested 10 applications
-- Example administrator updates:
-- update public.account_entitlements set tier='supporter',supporter=true,max_apps=5,verified_at=now() where user_id='<uuid>';
-- update public.account_entitlements set tier='pro',pro=true,supporter=true,max_apps=10,verified_at=now() where user_id='<uuid>';

commit;
