-- InstallerLab Analytics schema
-- The public client can only call the two RPC functions below. Raw event rows
-- are not exposed through PostgREST, and no service_role key is needed.

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  track_id text not null check (track_id ~ '^[A-Za-z0-9._:-]{8,80}$'),
  event_type text not null check (event_type in (
    'install_started', 'install_succeeded', 'install_failed',
    'uninstall_completed', 'launch', 'custom'
  )),
  event_at timestamptz not null default timezone('utc', now()),
  install_id text check (install_id is null or char_length(install_id) <= 80),
  app_name text check (app_name is null or char_length(app_name) <= 160),
  app_version text check (app_version is null or char_length(app_version) <= 80),
  package_type text check (package_type is null or char_length(package_type) <= 40),
  architecture text check (architecture is null or char_length(architecture) <= 40),
  windows_version text check (windows_version is null or char_length(windows_version) <= 80),
  language text check (language is null or char_length(language) <= 20),
  result text check (result is null or char_length(result) <= 40),
  duration_ms integer check (duration_ms is null or duration_ms between 0 and 86400000),
  error_code text check (error_code is null or char_length(error_code) <= 120),
  stage text check (stage is null or char_length(stage) <= 120),
  properties jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists analytics_events_track_time_idx
  on public.analytics_events (track_id, event_at desc);
create index if not exists analytics_events_track_type_idx
  on public.analytics_events (track_id, event_type);

alter table public.analytics_events enable row level security;
revoke all on table public.analytics_events from anon, authenticated;

create or replace function public.ingest_analytics_event(p_event jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
  v_track_id text;
  v_event_type text;
  v_props jsonb;
begin
  if p_event is null or jsonb_typeof(p_event) <> 'object' then
    raise exception 'Analytics event must be a JSON object';
  end if;
  if pg_column_size(p_event) > 8192 then
    raise exception 'Analytics event is too large';
  end if;

  v_track_id := left(trim(coalesce(p_event->>'track_id', '')), 80);
  v_event_type := lower(left(trim(coalesce(p_event->>'event_type', '')), 40));
  if v_track_id = '' or v_track_id !~ '^[A-Za-z0-9._:-]{8,80}$' then
    raise exception 'Invalid TrackID';
  end if;
  if v_event_type not in ('install_started', 'install_succeeded', 'install_failed', 'uninstall_completed', 'launch', 'custom') then
    raise exception 'Invalid analytics event type';
  end if;

  v_props := case
    when jsonb_typeof(p_event->'properties') = 'object' then p_event->'properties'
    else '{}'::jsonb
  end;

  insert into public.analytics_events (
    track_id, event_type, event_at, install_id, app_name, app_version,
    package_type, architecture, windows_version, language, result,
    duration_ms, error_code, stage, properties
  ) values (
    v_track_id,
    v_event_type,
    coalesce(nullif(p_event->>'event_at', '')::timestamptz, timezone('utc', now())),
    left(nullif(trim(p_event->>'install_id'), ''), 80),
    left(nullif(trim(p_event->>'app_name'), ''), 160),
    left(nullif(trim(p_event->>'app_version'), ''), 80),
    left(nullif(trim(p_event->>'package_type'), ''), 40),
    left(nullif(trim(p_event->>'architecture'), ''), 40),
    left(nullif(trim(p_event->>'windows_version'), ''), 80),
    left(nullif(trim(p_event->>'language'), ''), 20),
    left(nullif(trim(p_event->>'result'), ''), 40),
    case when coalesce(p_event->>'duration_ms', '') ~ '^\d+$' then (p_event->>'duration_ms')::integer else null end,
    left(nullif(trim(p_event->>'error_code'), ''), 120),
    left(nullif(trim(p_event->>'stage'), ''), 120),
    v_props
  ) returning id into v_id;

  return jsonb_build_object('accepted', true, 'id', v_id);
exception
  when invalid_text_representation then
    raise exception 'Invalid event timestamp';
end;
$$;

create or replace function public.analytics_summary(
  p_track_id text,
  p_from timestamptz default timezone('utc', now()) - interval '30 days',
  p_to timestamptz default timezone('utc', now())
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_track_id text := left(trim(coalesce(p_track_id, '')), 80);
  v_from timestamptz := coalesce(p_from, timezone('utc', now()) - interval '30 days');
  v_to timestamptz := coalesce(p_to, timezone('utc', now()));
  v_result jsonb;
begin
  if v_track_id = '' or v_track_id !~ '^[A-Za-z0-9._:-]{8,80}$' then
    raise exception 'Invalid TrackID';
  end if;
  if v_to < v_from then
    raise exception 'Invalid analytics date range';
  end if;

  with scoped as (
    select * from public.analytics_events
    where track_id = v_track_id and event_at >= v_from and event_at <= v_to
  ), versions as (
    select coalesce(app_version, 'Unknown') as label, count(*)::int as installs,
      count(*) filter (where event_type = 'install_succeeded')::int as successful,
      count(*) filter (where event_type = 'install_failed')::int as failed
    from scoped where event_type in ('install_succeeded', 'install_failed')
    group by coalesce(app_version, 'Unknown') order by installs desc
  ), platforms as (
    select coalesce(architecture, 'Unknown') as label, count(*)::int as value
    from scoped group by coalesce(architecture, 'Unknown') order by value desc
  ), windows as (
    select coalesce(windows_version, 'Unknown') as label, count(*)::int as value
    from scoped group by coalesce(windows_version, 'Unknown') order by value desc
  ), recent as (
    select jsonb_agg(to_jsonb(r) order by r.event_at desc) as rows
    from (
      select event_at, app_version, package_type, event_type, result,
        jsonb_build_object('architecture', architecture, 'windows_version', windows_version, 'language', language) as system
      from scoped order by event_at desc limit 50
    ) r
  )
  select jsonb_build_object(
    -- An installation is counted once when setup starts. Outcome events are
    -- reported separately as successful/failed, so one run is not double-counted.
    'installs', (select count(*) from scoped where event_type = 'install_started'),
    'started', (select count(*) from scoped where event_type = 'install_started'),
    'successful', (select count(*) from scoped where event_type = 'install_succeeded'),
    'failed', (select count(*) from scoped where event_type = 'install_failed'),
    'uninstalls', (select count(*) from scoped where event_type = 'uninstall_completed'),
    'launches', (select count(*) from scoped where event_type = 'launch'),
    'active_installs', (select count(distinct install_id) from scoped where event_type = 'install_succeeded' and install_id is not null),
    'versions', coalesce((select jsonb_agg(to_jsonb(versions)) from versions), '[]'::jsonb),
    'platforms', coalesce((select jsonb_agg(to_jsonb(platforms)) from platforms), '[]'::jsonb),
    'windows', coalesce((select jsonb_agg(to_jsonb(windows)) from windows), '[]'::jsonb),
    'recent_events', coalesce((select rows from recent), '[]'::jsonb),
    'from', v_from,
    'to', v_to
  ) into v_result;
  return v_result;
end;
$$;

revoke all on function public.ingest_analytics_event(jsonb) from public;
revoke all on function public.analytics_summary(text, timestamptz, timestamptz) from public;
grant execute on function public.ingest_analytics_event(jsonb) to anon, authenticated;
grant execute on function public.analytics_summary(text, timestamptz, timestamptz) to anon, authenticated;
